ALTER TABLE "premios" ADD COLUMN IF NOT EXISTS "custo_pontos" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "premios" ADD COLUMN IF NOT EXISTS "imagem_url" TEXT;
ALTER TABLE "premios" DROP COLUMN IF EXISTS "pontos";
