ALTER TYPE "TipoUsuario" ADD VALUE IF NOT EXISTS 'BACKOFFICE';
ALTER TYPE "TipoUsuario" ADD VALUE IF NOT EXISTS 'SUPERVISAO';
ALTER TYPE "TipoUsuario" ADD VALUE IF NOT EXISTS 'GERENCIA';
ALTER TYPE "TipoUsuario" ADD VALUE IF NOT EXISTS 'GESTOR_PJ';

ALTER TYPE "PapelGestor" ADD VALUE IF NOT EXISTS 'BACKOFFICE';
ALTER TYPE "PapelGestor" ADD VALUE IF NOT EXISTS 'GESTOR_PF';
